export const categorydata = [
  "Electronics",
  "Fashion",
  "Home & Kitchen",
  "Beauty",
  "Sports",
  "Automotive",
];

// export const mockdata = [
//   {
//     id: 1,
//     image: "./kid.jpeg",
//     name: "kid1",
//     price: 22,
//   },
//   {
//     id: 2,
//     image: "./women.jpeg",
//     name: "women1",
//     price: 223,
//   },
//   {
//     id: 3,
//     image: "./men.webp",
//     name: "men1",
//     price: 22,
//   },
//   {
//     id: 4,
//     image: "./womenn.jpg",
//     name: "women2",
//     price: 222,
//   },
//   {
//     id: 5,
//     image: "./kid.jpeg",
//     name: "kid2",
//     price: 222,
//   },
// ];

export const shopData = [
  {
    brand: "Urbano Fashino",
    name: "US Polo",
    price: "799",
    size: "32,34",
    category: "men",
    id: "m1",
    img: "https://rukminim2.flixcart.com/image/612/612/xif0q/shopsy-shirt/3/6/9/s-spc-csrmnkt-maroon-voroxy-original-imagsz78ukkf4rgb.jpeg?q=70",
  },
  {
    brand: "saila",
    name: "Road Star",
    price: "899",
    size: "32,34",
    category: "men",
    id: "m7",
    img: "https://rukminim2.flixcart.com/image/612/612/xif0q/t-shirt/j/k/g/s-xyptsrt11-xyxx-original-imagrh83aj6h4y62.jpeg?q=70",
  },
  {
    brand: "Killer",
    name: "Nike",
    price: "1599",
    size: "32,34",
    category: "men",
    id: "m12",
    img: "https://rukminim2.flixcart.com/image/612/612/l4zxn680/jean/o/q/d/32-18298-1228-levi-s-original-imagfrrecq69kmkn.jpeg?q=70",
  },
  {
    brand: "Killer",
    name: "Calvin Klein",
    price: "1999",
    size: "32,34",
    category: "men",
    id: "m4",
    img: "https://rukminim2.flixcart.com/image/612/612/xif0q/shirt/p/2/q/-original-imags23nszvhkhfd.jpeg?q=70",
  },

  {
    brand: "Killer",
    name: "US Polo",
    price: "899",
    size: "32,34",
    category: "men",
    id: "m3",
    img: "https://rukminim2.flixcart.com/image/612/612/xif0q/shirt/f/a/g/xl-m24121-blue-blue-buddha-original-imagqbrgbfzjpn8h.jpeg?q=70",
  },

  {
    brand: "Killer",
    name: "Calvin Klein",
    price: "1199",
    size: "32,34",
    category: "men",
    id: "m5",
    img: "https://rukminim2.flixcart.com/image/612/612/xif0q/shirt/0/2/l/m-bhmlslv23003-grey-being-human-original-imagpe9zkpyntnmf.jpeg?q=70",
  },
  {
    brand: "saila",
    name: "Road Star",
    price: "699",
    size: "32,34",
    category: "men",
    id: "m8",
    img: "https://rukminim2.flixcart.com/image/612/612/xif0q/t-shirt/2/9/y/m-bylrn-z31-blive-original-imaggdk9bjtk2hf4.jpeg?q=70",
  },
  {
    brand: "Road Star",
    name: "Calvin Klein",
    price: "499",
    size: "32,34",
    category: "men",
    id: "m6",
    img: "https://rukminim2.flixcart.com/image/612/612/xif0q/t-shirt/q/j/b/l-rhp1554-red-tape-original-imagnefczce3m2hr.jpeg?q=70",
  },

  {
    brand: "Road Star",
    name: "Nike",
    price: "1799",
    size: "32,34",
    category: "men",
    id: "m11",
    img: "https://rukminim2.flixcart.com/image/612/612/xif0q/jean/8/9/3/-original-imagsqbzp8gzfmcz.jpeg?q=70",
  },
  {
    brand: "Saila",
    name: "Road Star",
    price: "899",
    size: "32,34",
    category: "men",
    id: "m9",
    img: "https://rukminim2.flixcart.com/image/612/612/xif0q/t-shirt/r/v/k/m-ausk0165-ausk-original-imaghu9fbhcgf2za.jpeg?q=70",
  },
  {
    brand: "Killer",
    name: "Road Star",
    price: "999",
    size: "32,34",
    category: "men",
    id: "m10",
    img: "https://rukminim2.flixcart.com/image/612/612/xif0q/jean/o/g/2/34-bhdi22618-being-human-original-imagjyksmczjtvdb.jpeg?q=70",
  },

  {
    brand: "Urbano Fashino",
    name: "US Polo",
    price: "599",
    size: "32,34",
    category: "men",
    id: "m2",
    img: "https://rukminim2.flixcart.com/image/612/612/xif0q/shirt/o/j/t/-original-imags23pqg87sxv9.jpeg?q=70",
  },
  {
    brand: "Killer",
    name: "Nike",
    price: "899",
    size: "32,34",
    category: "men",
    id: "m13",
    img: "https://rukminim2.flixcart.com/image/612/612/xif0q/jean/2/a/l/34-bootep-iceblue-urbano-fashion-original-imagnhyjmu7zbxym.jpeg?q=70",
  },
  {
    brand: "urbano fashino",
    name: "Nike",
    price: "499",
    size: "24",
    category: "kid",
    id: "v",
    img: "https://rukminim2.flixcart.com/image/832/832/xif0q/kids-apparel-combo/b/1/d/2-3-years-printed-emblica-original-imagpyf2jdmubycn.jpeg?q=70",
  },
  {
    brand: "Lens",
    name: "Nike",
    price: "474",
    size: "24",
    category: "kid",
    id: "v1",
    img: "https://rukminim2.flixcart.com/image/832/832/xif0q/kids-t-shirt/x/k/u/5-6-years-na-41761-smartraho-original-imagzgchqcwde5ph.jpeg?q=70",
  },
  {
    brand: "King",
    name: "Nike",
    price: "1399",
    size: "24",
    category: "kid",
    id: "v2",
    img: "https://rukminim2.flixcart.com/image/832/832/xif0q/suit/e/y/k/11-12-years-s-205-royal-blue-bt-dezines-original-imags5fvftuz6dyx.jpeg?q=70",
  },
  {
    brand: "urbano fashino",
    name: "Road Star",
    price: "259",
    size: "24",
    category: "kid",
    id: "v3",
    img: "https://rukminim2.flixcart.com/image/832/832/xif0q/kids-ethnic-set/t/z/q/6-12-months-kurta-with-platting-dhoti-new-gen-original-imafmjtxmpjkbywx-bb.jpeg?q=70",
  },
  {
    brand: "urbano fashino",
    name: "Road Star",
    price: "295",
    size: "24",
    category: "kid",
    id: "v4",
    img: "https://rukminim2.flixcart.com/image/832/832/xif0q/kids-ethnic-set/i/g/n/5-6-years-ffw-002ye-farishta-fashion-original-imagguxfbtbmkdy5.jpeg?q=70",
  },
  {
    brand: "Lens",
    name: "Road Star",
    price: "284",
    size: "24",
    category: "kid",
    id: "v5",
    img: "https://rukminim2.flixcart.com/image/832/832/xif0q/kids-ethnic-set/y/g/z/12-18-months-stc-krishna001-evaan-enterprises-original-imafswuw66ykjhev-bb.jpeg?q=70",
  },
  {
    brand: "urbano fashino",
    name: "US Polo",
    price: "899",
    size: "24",
    category: "kid",
    id: "v6",
    img: "https://rukminim2.flixcart.com/image/832/832/xif0q/kids-apparel-combo/5/i/7/9-10-years-lbcmbtj04-xy-life-original-imagjkkbjchmyxbp.jpeg?q=70",
  },
  {
    brand: "Lens",
    name: "US Polo",
    price: "469",
    size: "24",
    category: "kid",
    id: "v7",
    img: "https://rukminim2.flixcart.com/image/832/832/xif0q/shirt/h/u/l/8-9-years-kdschden-carbonn-clozz-original-imagqygmwh3nhtng.jpeg?q=70",
  },
  {
    brand: "urbano fashino",
    name: "US Polo",
    price: "1799",
    size: "24",
    category: "kid",
    id: "v8",
    img: "https://rukminim2.flixcart.com/image/832/832/xif0q/suit/5/j/3/12-18-months-s-205-wine-bt-dezines-original-imags5ehreqnhsrr.jpeg?q=70",
  },
  {
    brand: "King",
    name: "US Polo",
    price: "449",
    size: "24",
    category: "kid",
    id: "v9",
    img: "https://rukminim2.flixcart.com/image/832/832/xif0q/kids-ethnic-set/p/l/u/0-6-months-ang-red-little-dreams-original-imagahepm4qwbd6d-bb.jpeg?q=70",
  },
  {
    brand: "urbano fashino",
    name: "US Polo",
    price: "280",
    size: "24",
    category: "kid",
    id: "v10",
    img: "https://rukminim2.flixcart.com/image/832/832/xif0q/kids-ethnic-set/w/u/c/6-12-months-lu-kt-dt-dp-gld-looks-united-original-imafczcdzycvfhd5-bb.jpeg?q=70",
  },
  {
    brand: "urbano fashino",
    name: "Nike",
    price: "284",
    size: "24",
    category: "kid",
    id: "v11",
    img: "https://rukminim2.flixcart.com/image/832/832/kq2o2vk0/kids-ethnic-set/a/w/j/3-6-months-with-jwellrey-rkc-original-imag45upzgsvfe8j.jpeg?q=70",
  },
  {
    brand: "urbano fashino",
    name: "meesho",
    price: "868",
    size: "34",
    category: "women",
    id: "w1",
    img: "https://rukminim2.flixcart.com/image/832/832/xif0q/dress/8/t/m/xl-gd-008-light-blue-glamoda-original-imagpn9fwwhdfkgw.jpeg?q=70",
  },
  {
    brand: "urbano fashino",
    name: "meesho",
    price: "499",
    size: "34",
    category: "women",
    id: "w2",
    img: "https://rukminim2.flixcart.com/image/477/477/xif0q/dress/d/8/0/3xl-chiku-kittari-fashion-original-imaggvwz2dtu96dz.jpeg?q=70",
  },
  {
    brand: "urbano fashino",
    name: "meesho",
    price: "359",
    size: "34",
    category: "women",
    id: "w3",
    img: "https://rukminim2.flixcart.com/image/612/612/kjd6nww0-0/dress/5/d/4/m-cfrk152-160-hiva-trendz-original-imafyyk5c7ffmghy.jpeg?q=70",
  },
  {
    brand: "urbano fashino",
    name: "Nike",
    price: "650",
    size: "34",
    category: "women",
    id: "w4",
    img: "https://rukminim2.flixcart.com/image/612/612/xif0q/jumpsuit/w/f/o/s-sfjmps8255-sassafras-original-imagzj8u9gq2hnh7.jpeg?q=70",
  },
  {
    brand: "urbano fashino",
    name: "Nike",
    price: "699",
    size: "34",
    category: "women",
    id: "w5",
    img: "https://rukminim2.flixcart.com/image/832/832/xif0q/lehenga-choli/i/c/f/free-3-4-sleeve-1006-lehenga-choli-vucci-original-imaghmpvwhur7kwr.jpeg?q=70",
  },
  {
    brand: "urbano fashino",
    name: "Nike",
    price: "999",
    size: "34",
    category: "women",
    id: "w6",
    img: "https://rukminim2.flixcart.com/image/832/832/l4bn5ow0/kurta/0/l/g/l-ram-lakhan-gown1-tashwicreation-original-imagf8zdgwqfdafq.jpeg?q=70",
  },
  {
    brand: "urbano fashino",
    name: "Calvin Klein",
    price: "377",
    size: "34",
    category: "women",
    id: "w7",
    img: "https://rukminim2.flixcart.com/image/832/832/kzpw2vk0/dress/i/c/a/l-ttj6006657-tokyo-talkies-original-imagbz284y2exgvk.jpeg?q=70",
  },
  {
    brand: "urbano fashino",
    name: "Calvin Klein",
    price: "699",
    size: "34",
    category: "women",
    id: "w8",
    img: "https://rukminim2.flixcart.com/image/784/784/xif0q/lehenga-choli/j/u/x/free-short-sleeve-d-no-101-lehengacholi-jinnar-original-imaghzpnq4sz3cgj.jpeg?q=70",
  },
  {
    brand: "urbano fashino",
    name: "Calvin Klein",
    price: "609",
    size: "34",
    category: "women",
    id: "w9",
    img: "https://rukminim2.flixcart.com/image/612/612/kqb8pzk0/jumpsuit/z/6/y/l-ser-jumpsuit-as-1-serein-original-imag4cmhsrernezn.jpeg?q=70",
  },
  {
    brand: "urbano fashino",
    name: "meesho",
    price: "739",
    size: "34",
    category: "women",
    id: "w10",
    img: "https://rukminim2.flixcart.com/image/612/612/xif0q/gown/b/a/d/n-a-s-3-4-sleeve-stitched-r81-ftdiva-n-a-original-imagg2znwfwudqkc.jpeg?q=70",
  },
  {
    brand: "urbano fashino",
    name: "keeln",
    price: "359",
    size: "34",
    category: "women",
    id: "w11",
    img: "https://rukminim2.flixcart.com/image/612/612/kjbr8280-0/dress/x/h/h/l-cfrk183-188-hiva-trendz-original-imafywxp8v89nwvc.jpeg?q=70",
  },
  {
    brand: "urbano fashino",
    name: "Nike",
    price: "493",
    size: "34",
    category: "women",
    id: "w12",
    img: "https://rukminim2.flixcart.com/image/832/832/xif0q/pyjama/i/b/b/m-womennpyjamaplainp-trendy-world-original-imaghekvvcpbxyep.jpeg?q=70",
  },
  {
    name: "motorola edge 40",
    brand: " motorola",
    price: " Rs:25249",
    size: "6.2 ",
    category: "Electronics",
    id: "s1 ",
    img: " https://rukminim2.flixcart.com/image/312/312/xif0q/mobile/2/m/o/edge-40-pay40030in-motorola-original-imagpqzchzhg6fex.jpeg?q=70 ",
  },

  {
    name: "oppo reno10 5g",
    brand: "oppo ",
    price: "32999 ",
    size: " 6.7",
    category: "Electronics",
    id: "s2",
    img: " https://rukminim2.flixcart.com/image/312/312/xif0q/mobile/9/e/4/-original-imagtcrumzbqj4xd.jpeg?q=70 ",
  },

  {
    name: "realme 11pro 5g",
    brand: "realme ",
    price: " 24999",
    size: "6.7 ",
    category: "Electronics",
    id: "s3 ",
    img: " https://rukminim2.flixcart.com/image/312/312/xif0q/mobile/l/8/d/-original-imagqadpnygfnn2v.jpeg?q=70 ",
  },

  {
    name: "vivo T2 pro 5G",
    brand: "vivo ",
    price: "24999 ",
    size: "6.78 ",
    category: "Electronics",
    id: "s4 ",
    img: " https://rukminim2.flixcart.com/image/312/312/xif0q/mobile/g/b/x/-original-imagtt4h4ptmxgwn.jpeg?q=70 ",
  },

  {
    name: "Lenovo ldeapad ",
    brand: "lenovo ",
    price: "68990 ",
    size: "15.6 ",
    category: "Electronics",
    id: "s5 ",
    img: " https://rukminim2.flixcart.com/image/312/312/xif0q/computer/i/y/m/-original-imagu3kmq9f2tapj.jpeg?q=70 ",
  },

  {
    name: "HP 2023 Athlon Dual",
    brand: "HP ",
    price: "28990 ",
    size: " 15.6",
    category: "Electronics",
    id: "s6 ",
    img: " https://rukminim2.flixcart.com/image/312/312/xif0q/computer/5/6/i/-original-imaggshd5zgfe8ev.jpeg?q=70 ",
  },

  {
    name: "ASUS Vivobook 15",
    brand: "ASUS ",
    price: " 32990",
    size: "15.6 ",
    category: " Electronics",
    id: "s7 ",
    img: " https://rukminim2.flixcart.com/image/312/312/xif0q/computer/q/e/z/-original-imagpxgqesgrthks.jpeg?q=70 ",
  },

  {
    name: "Acer Extensa(2023)",
    brand: "Acer ",
    price: " 26990",
    size: " 15.6",
    category: "Electronics",
    id: "s8 ",
    img: " https://rukminim2.flixcart.com/image/312/312/xif0q/computer/7/o/r/-original-imagnc38zedzfnw6.jpeg?q=70 ",
  },

  {
    name: "Mi 5A ",
    brand: " Mi",
    price: "11499 ",
    size: "32 ",
    category: "Electronics",
    id: "s9 ",
    img: " https://rukminim2.flixcart.com/image/312/312/xif0q/television/t/q/f/-original-imagt86kc5jttkxa.jpeg?q=70 ",
  },

  {
    name: "One Plus U1S",
    brand: "One Plus ",
    price: "50999 ",
    size: "65 ",
    category: "Electronics",
    id: "s10 ",
    img: " https://rukminim2.flixcart.com/image/312/312/kuwzssw0/television/u/i/r/u-series-65-u1s-65uc1a00-oneplus-original-imag7xtnmnkyz7je.jpeg?q=70 ",
  },

  {
    name: "Motorola Envision X",
    brand: "motorola ",
    price: " 10999",
    size: " 32",
    category: "Electronics",
    id: "s11 ",
    img: " https://rukminim2.flixcart.com/image/312/312/xif0q/television/j/1/2/32hdgdmwsbe-motorola-original-imagrwh5ghsevqnf.jpeg?q=70 ",
  },

  {
    name: "Samsung LED smart tizen",
    brand: "Samsung ",
    price: "12490 ",
    size: "32 ",
    category: "Electronics ",
    id: "s12 ",
    img: " https://rukminim2.flixcart.com/image/312/312/xif0q/television/x/8/a/-original-imagttjpuyzsbzud.jpeg?q=70 ",
  },
];
